# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-25 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Put_Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='000', max_length=5, verbose_name='id')),
                ('what_put', models.CharField(default='', max_length=255, verbose_name='\u63d0\u4f9bwhat')),
                ('time_zone', models.CharField(default='', max_length=20, verbose_name='\u65f6\u95f4\u6bb5')),
                ('money', models.CharField(default='', max_length=10)),
                ('status', models.IntegerField(choices=[(1, '\u51bb\u7ed3'), (2, '\u6b63\u5e38')], default=2, verbose_name='\u72b6\u6001')),
                ('note', models.CharField(default='', max_length=50, null=True, verbose_name='\u5907\u6ce8')),
                ('add_time', models.DateTimeField()),
            ],
        ),
    ]
